repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-json
    -   id: check-yaml
    -   id: check-vcs-permalinks
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

- repo: https://github.com/markdownlint/markdownlint
  rev: v0.11.0
  hooks:
  - id: markdownlint
    args: ["-r", "~MD013"]

- repo: local
  hooks:
  - id: cargo-fmt
    name: cargo fmt
    description: "Format the package using cargo fmt"
    language: rust
    types: [rust]
    entry: cargo fmt
    args: ["--"]

- repo: local
  hooks:
  - id: cargo-check
    name: cargo check
    description: "Check the package for errors using cargo check."
    language: rust
    types: [rust]
    entry: cargo check
    pass_filenames: false
